# Generated by Django 5.2.7 on 2025-10-04 07:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('delivery_date', models.DateTimeField()),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_completed_order', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_completed_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^0\\d{10}$', 'Mobile number should be 11 digits starting with 0.')])),
                ('city_town', models.CharField(max_length=30)),
                ('prominent_motor_park', models.CharField(blank=True, max_length=50, null=True)),
                ('landmark_signatory_place', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('shipped', models.BooleanField(default=False)),
                ('estimated_delivery_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lga_pending_order', to='base.lga')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_pending_order', to='products.product')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_pending_order', to='base.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pending_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_town', models.CharField(max_length=30)),
                ('prominent_motor_park', models.CharField(blank=True, max_length=50, null=True)),
                ('landmark_signatory_place', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('lga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_lga', to='base.lga')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_state', to='base.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('other_name', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alternative_phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^0\\d{10}$', 'Mobile number should be 11 digits starting with 0.')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
