# Generated by Django 5.2.7 on 2025-10-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deals'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
